#!/usr/bin/env bash
set -e


die() {
    printf "$1\n" >&2
    show_cursor
    exit 1
}

hdr() {
    if $SINGLE_LINE; then
        # Clear line and overwrite
        printf "\r%*s" "$(tput cols)" "" >&2
        printf "\r$*" >&2
    else
        printf "$*\n" >&2
    fi
}

gitcmd() {
    local repopath="$1"
    local subcmd="$2"
    local output=
    local r=

    set +e
    if [ "$subcmd" == clone ]; then
        output=$(GIT_TERMINAL_PROMPT=0 git $subcmd ${@:3} "$repopath" 2>&1)
        r=$?
    else
        output=$(git -C "$repopath" $subcmd ${@:3} 2>&1)
        r=$?
    fi
    set -e

    # shellcheck disable=SC2181
    if [ $r != 0 ]; then
        hdr "${repopath##"$PLG_PREFIX/"}: \033[91m${subcmd^} failed\033[0m"
        $SINGLE_LINE && echo
        echo "$output"
        show_cursor
        exit $r
    else
        echo -n "$output"
    fi
}

hide_cursor() { printf '\033[?25l'; }

show_cursor() { printf '\x1b[?25h'; }

usage() {
    local yellow=$(printf "\033[${Y}m")
    local green=$(printf "\033[${G}m")
    local reset=$(printf "\033[0m")
    cat << EOF >&2
Usage: plg [OPTIONS] <COMMAND>

${yellow}COMMANDS:${reset}
  ${green}sy(nc)${reset}        Sync and patch all plugins
  ${green}st(atus)${reset}      Show status
  ${green}c(lean)${reset}       Delete stray pacakges
  ${green}p(atch)${reset}       Apply patches onto all plugins
  ${green}u(npatch)${reset}     Unpatch all plugins

${yellow}OPTIONS:${reset}
    ${green}-j${reset}          Job count for syncing [default: $PLG_JOBS]
    ${green}-s${reset}          Print output on single line

${yellow}ENVIRONMENT:${reset}
  ${green}PLG_PLUGINS${reset}          Path to configuration file, should export PKGS=() and optionally PATCHES=()
  ${green}PLG_PREFIX${reset}           Path to clone repositories into, needs to be on runtimepath
  ${green}PLG_PATCHDIR${reset}         Path to patches

EOF
    exit 1
}

job_unpatch() {
    local name="$1"
    local repo="$PLG_PREFIX/$(basename $name)"
    if [ ! -d "$repo" ]; then
        return
    fi

    local output=$(gitcmd $repo checkout .)
    if [ "$output" != "Updated 0 paths from the index" ]; then
        hdr "$name: \033[${G}m$output\033[0m"
    fi

    # Skip parser*/ directories for nvim-treesitter
    output=$(gitcmd $repo clean \
        --exclude=parser \
        --exclude=parser-info \
        --exclude=.tags \
        --exclude=.luarc.json \
        -fdx)

    if [ -n "$output" ]; then
        hdr "$name: \033[${G}m$output\033[0m"
    fi
}

job_sync_repo() {
    local remotepath="$1"

    if [[ "$remotepath" == *://* ]]; then
        local url="$remotepath"
    else
        local url="https://github.com/$remotepath"
    fi

    mkdir -p "$PLG_PREFIX"
    local outdir="$PLG_PREFIX/$(basename $remotepath)"

    if [ -d "$outdir" ]; then
        local output=$(gitcmd $outdir pull)
        # Print which commit we are updating to if applicable, otherwise
        # use the first line from the output.
        local outstr=$(grep -E '^Updating ' <<< "$output")
        if [ -z "$outstr" ]; then
            outstr=$(sed -n '1p' <<< "$output")
        fi
        hdr "$remotepath: \033[${G}m$outstr\033[0m"
    else
        local _=$(gitcmd $outdir clone -c advice.detachedHead=false --depth $PLG_CLONE_DEPTH "$url")
        local git_ref=$(gitcmd $outdir rev-parse --short HEAD)
        hdr "$remotepath: \033[${G}mCloned $git_ref\033[0m"
    fi
}

plg_sync() {
    local i=0
    local pids=()
    for pkg in ${PKGS[@]}; do
        job_sync_repo $pkg &
        pids+=($!)

        # Clone PLG_JOBS repos at a time
        if [ $((i % PLG_JOBS)) = $((PLG_JOBS - 1)) ]; then
            wait ${pids[@]}
        fi
        i=$((i + 1))
    done

    wait ${pids[@]}

    plg_patch
}

plg_unpatch() {
    for pkg in ${PKGS[@]}; do
        job_unpatch $pkg
    done
}

plg_patch() {
    [ -z "${PATCHES[*]}" ] && return

    for p in ${PATCHES[@]}; do
        gitcmd $PLG_PREFIX/$p apply "$PLG_PATCHDIR/$(basename "$p").patch"
        local remotepath="$(tr ' ' '\n' <<< "${PKGS[*]}" | grep "$p$")"
        hdr "$remotepath: \033[${G}mPatched successfully\033[0m"
    done
}

plg_status() {
    for pkg in ${PKGS[@]}; do
        local repo="$PLG_PREFIX/$(basename "$pkg")"
        if [ -z "$repo" ]; then
            echo "Not found: $pkg" >&2
            continue
        fi

        # * Try tag name
        local refname=$(git -C $repo tag --points-at HEAD 2> /dev/null | head -n1)
        # * Try branch name
        [ -z "$refname" ] &&
            local refname=$(git -C $repo symbolic-ref --short HEAD 2> /dev/null)
        [ -n "$refname" ] && refname="[$refname]"
        printf "$pkg \033[${G}m$refname\033[0m\n" >&2

        git -c color.status=always -C "$repo" status -s
    done
}

plg_clean() {
    local cleaned=false
    for d in "$PLG_PREFIX"/*; do
        local name=$(basename $d)
        if ! grep -qE "/${name}\s+" <<< "${PKGS[*]} "; then
            echo "Removing stray package: $name"
            rm -rf ${d}
            cleaned=true
        fi
    done
    $cleaned || echo "No stray packages"
}

################################################################################

# Exports PKGS and PATCHES
PLG_PLUGINS=${PLG_PLUGINS:-$HOME/.config/nvim/plugins.sh}
PLG_PATCHDIR="${PLG_PATCHDIR:-$HOME/.config/nvim/patches}"
# Skip support for .../opt/
PLG_PREFIX=${PLG_PREFIX:-"$HOME/.local/share/nvim/site/pack/plg/start"}
PLG_CLONE_DEPTH=${PLG_CLONE_DEPTH:-1}
PLG_JOBS=8
SINGLE_LINE=false
G=92
Y=93

# shellcheck disable=SC1090
source "$PLG_PLUGINS"

trap show_cursor INT

while getopts ":hj:s" opt; do
    case $opt in
    j) PLG_JOBS=$OPTARG ;;
    s) SINGLE_LINE=true ;;
    *) usage ;;
    esac
done

shift $((OPTIND - 1))

mkdir -p $PLG_PREFIX

case "$1" in
sy*)
    hide_cursor
    plg_unpatch
    plg_sync
    $SINGLE_LINE && echo
    show_cursor
;;
u*)
    hide_cursor
    plg_unpatch
    $SINGLE_LINE && echo
    show_cursor
;;
st*) plg_status ;;
p*) plg_patch ;;
c*) plg_clean ;;
*) usage ;;
esac
